spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/decoration?characterEncoding=UTF-8&amp;rewriteBatchedStatements=true&amp;allowMultiQueries=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.decoration.dao.enetity

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
